import { Campaign } from "./CampaignCard";

export const campaigns: Campaign[] = [
  {
    id: 1,
    tag: "🏥 Medical",
    urgent: true,
    gradient: "linear-gradient(135deg, #2D5A8E 0%, #5B9BD5 100%)",
    avatarGradient: "linear-gradient(135deg, #2D5A8E, #5B9BD5)",
    initials: "SR",
    creator: "Sarah Rahman",
    title: "Help cover Maya's life-saving heart surgery at AIIMS Delhi",
    description: "Maya is a 7-year-old with a congenital heart defect that requires immediate surgical intervention. Her family has exhausted all savings and needs community support to fund the procedure at AIIMS.",
    raised: "$36,500",
    goal: "$50,000",
    pct: 68,
    donors: 412,
    daysLeft: 18,
    featured: true,
    saved: true,
    links: ["link1", "link2", "link3", ""]
  },
  {
    id: 2,
    tag: "🏥 Medical",
    gradient: "linear-gradient(135deg, #C0442A 0%, #E8820C 100%)",
    avatarGradient: "linear-gradient(135deg, #C0442A, #E8820C)",
    initials: "JM",
    creator: "James Mitchell",
    title: "Fund Aiden's leukemia treatment — 3 cycles remaining",
    raised: "$21,000",
    goal: "$50,000",
    pct: 42,
    donors: 238,
    daysLeft: 12,
    featured: false,
    saved: true,
    links: ["link1", "link2", "", ""]
  },
  {
    id: 3,
    tag: "🏥 Medical",
    urgent: true,
    gradient: "linear-gradient(135deg, #8B3A52 0%, #C0567A 100%)",
    avatarGradient: "linear-gradient(135deg, #8B3A52, #C0567A)",
    initials: "PK",
    creator: "Priya Kapoor",
    title: "Spinal surgery for Rohan, 34 — accident left him paralysed",
    raised: "$44,500",
    goal: "$50,000",
    pct: 89,
    donors: 601,
    daysLeft: 5,
    featured: true,
    saved: false,
    links: ["link1", "link2", "link3", "link4"]
  },
  {
    id: 4,
    tag: "🏥 Medical",
    gradient: "linear-gradient(135deg, #7B5EA7 0%, #B09FD4 100%)",
    avatarGradient: "linear-gradient(135deg, #7B5EA7, #B09FD4)",
    initials: "AN",
    creator: "Ananya Nair",
    title: "Dialysis costs for my mother — 3 sessions a week",
    raised: "$7,750",
    goal: "$25,000",
    pct: 31,
    donors: 89,
    daysLeft: 24,
    featured: false,
    saved: true,
    links: ["link1", "", "", ""]
  },
  {
    id: 5,
    tag: "🏥 Medical",
    gradient: "linear-gradient(135deg, #1A6B6B 0%, #3AAFA9 100%)",
    avatarGradient: "linear-gradient(135deg, #1A6B6B, #3AAFA9)",
    initials: "DV",
    creator: "Dev Verma",
    title: "Cochlear implant for Zara — give her the gift of sound",
    raised: "$16,800",
    goal: "$30,000",
    pct: 56,
    donors: 174,
    daysLeft: 31,
    featured: false,
    saved: false,
    links: ["link1", "link2", "", ""]
  },
  {
    id: 6,
    tag: "🏥 Medical",
    gradient: "linear-gradient(135deg, #4A6741 0%, #7DB56A 100%)",
    avatarGradient: "linear-gradient(135deg, #4A6741, #7DB56A)",
    initials: "RG",
    creator: "Riya Ghosh",
    title: "Bone marrow transplant for Kabir, 9 years old",
    raised: "$57,750",
    goal: "$75,000",
    pct: 77,
    donors: 823,
    daysLeft: 9,
    featured: true,
    saved: false,
    links: ["", "", "", ""],
  },
];